### ISSUE TITLE
Folder icon ugly

### ISSUE THREAD

**Issue by agileago** [leviothan/jetbrains-prime-ui#1]
this repository is so great ! but like this
![qq20160512-0 2x](https://cloud.githubusercontent.com/assets/11799110/15200286/de7fb5ac-1817-11e6-8d3a-a59f70397e8f.png)

the folder icons is so ugly , can you change the icon to replace it? thanks 

you can accord this  [https://github.com/iccir/El-Capitan-Theme](https://github.com/iccir/El-Capitan-Theme)

![qq20160512-1 2x](https://cloud.githubusercontent.com/assets/11799110/15200321/456abf00-1818-11e6-9f8d-e4b45a024f97.png)

we want a beautiful theme on jetbrains ide . isn't it ?

**Comment by leviothan** [comment]
@agileago thanks for the feedback!
I am was planning this icons for using with dark theme. Don't test it with light theme. 
i'll experiment with icons in the weekend.

P.S. I did not think that someone uses it, except me :)

**Comment by agileago** [comment]
thanks . because my color theme is dark. so i think the dark appearance will be hurt to eyes. and i want to find a theme like sublime light sidebar. i find your plugin is so similar with [https://github.com/JustSid/AfterglowIntelliJ](https://github.com/JustSid/AfterglowIntelliJ) (but afterglow only supply dark )

i am a stranger to java. i don't how to change the fileicon. sorry for disturbing you
